// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xpnqbhzyjtiqevvllmin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbnFiaHp5anRpcWV2dmxsbWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjQ4ODcsImV4cCI6MjA2NjY0MDg4N30.HZAWbl5UspKyaUto7u7ptMQdJ30GvL2JOY1PeohJIzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);